package ca.sheridancollege.dummy;

public enum owners {
	Sparkle_Old,
	Marketta_Newlin,
	Roseanne_Tinkle,
	Wan_Honey,
	Kittie_Diggins,
	Ingeborg_Kwiecien,
	Marline_Cornwell,
	Adria_Arcuri,
	Chelsie_Reising,
	Jordan_Romo,
	Cheri_Waltz,
	Nina_Sims,
	Ryann_Lowrey,
	Ira_Hoss,
	Audrey_Isenberg,
	Devora_Risk,
	Adina_Chesnut,
	Donn_Bovee,
	Rosemarie_Gardner,
	Theodore_Kesinger,
	Delbert_Hellman,
	Eleanor_Mendel,
	Shaunta_Galeana,
	Cathie_Wagnon,
	Mariko_Davison,
	Trey_Mariani,
	Mitchell_Clairmont,
	Lilly_Horiuchi,
	Valarie_Hadfield,
	Risa_Guider,
	Candie_Vawter,
	Erma_Morant,
	Raisa_Drayer,
	Joseph_Defrank,
	Edna_Portier,
	Tia_Burling,
	Gianna_Deschaine,
	Dyan_Gerard,
	Kathleen_Strang,
	Rodolfo_Leisure,
	Marquitta_Effler,
	Barbra_Demuth,
	Salome_Goodyear,
	Rosemary_Blanch,
	Reginald_Crigler,
	Agatha_Embree,
	Britt_Coatney,
	Lily_Zemke,
	Shanell_Stainback,
	Andy_Holst,
	Versie_Vise,
	Ingeborg_Iddings,
	Blanca_Bilski,
	Annalee_Anker,
	Geraldo_Guinyard,
	Steffanie_Silvey,
	Terra_Tatham,
	Marc_Mozingo,
	Ria_Ritzman,
	Sherise_Stellmacher,
	Rolando_Rasco,
	Merna_Marotta,
	Susanne_Salser,
	Ocie_Overall,
	Doreen_Damewood,
	Lexie_Leitner,
	Lenora_Lastinger,
	Zenaida_Zackery,
	Oralia_Ojeda,
	Darell_Donmoyer,
	Rona_Rutter,
	Rayford_Ridout,
	Carylon_Cusson,
	Marlana_Moring,
	Eulah_Eggleton,
	Elbert_Ebright,
	Damaris_Darrell,
	Addie_Ancona,
	Kristofer_Kerr,
	Page_Pablo,
	Chae_Colby,
	Rolanda_Rarick,
	Kaye_Knell;
	public static owners getRandom(){
		owners lettre = owners.values()[(int)(Math.random()*owners.values().length)];
		
		return lettre;
	    }
	public static String toString(owners b) {
		  String owner = b.toString();
		  owner = owner.replace("_", " ");
		  return owner;
	  }

	
}
